# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:

import torch

random_tensor = torch.rand(7, 7)

print(random_tensor)


 


tensor([[0.6865, 0.5456, 0.0615, 0.6399, 0.0312, 0.9273, 0.2199],
        [0.5244, 0.6721, 0.9672, 0.4174, 0.3113, 0.7339, 0.3956],
        [0.0576, 0.8536, 0.9446, 0.6443, 0.0080, 0.4208, 0.8496],
        [0.1473, 0.3022, 0.3497, 0.7699, 0.0374, 0.1034, 0.4627],
        [0.4262, 0.2523, 0.8202, 0.2181, 0.4786, 0.3577, 0.0451],
        [0.8214, 0.0613, 0.1859, 0.3020, 0.4626, 0.4545, 0.2987],
        [0.2565, 0.1093, 0.9093, 0.7762, 0.8432, 0.1039, 0.4118]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
import torch
random_tensor = torch.rand(7, 7)
other_tensor = torch.rand(1, 7)
result = torch.matmul(random_tensor, other_tensor.T)

print("Result shape:", result.shape)
print(result)



Result shape: torch.Size([7, 1])
tensor([[1.1694],
        [1.3718],
        [0.4467],
        [1.6366],
        [1.4269],
        [0.8152],
        [1.8129]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
import torch
torch.manual_seed(0)
random_tensor = torch.rand(7, 7)
other_tensor = torch.rand(1, 7)
result = torch.matmul(random_tensor, other_tensor.T)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
import torch

# Set CPU random seed
torch.manual_seed(0)

# Set GPU random seed (if CUDA is available)
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234")
else:
    print("CUDA not available, skipping GPU seed setup.")


CUDA not available, skipping GPU seed setup.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
import torch
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

print(tensor_a, tensor_b)



Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
import torch

# Set manual seed
torch.manual_seed(1234)

# Select device (GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors on the selected device
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

# Perform matrix multiplication (need to transpose tensor_b)
result = torch.matmul(tensor_a, tensor_b.T)

print(result, result.shape)



Device: cpu
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
import torch

# Set manual seed
torch.manual_seed(1234)

# Select device (GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create tensors
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

# Matrix multiplication
result = torch.matmul(tensor_a, tensor_b.T)

# Find max and min values
max_value = torch.max(result)
min_value = torch.min(result)

print("Result:\n", result)
print("Max value:", max_value)
print("Min value:", min_value)


Result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
Max value: tensor(0.5617)
Min value: tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:

import torch

# Set manual seed
torch.manual_seed(1234)

# Select device (GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create tensors
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

# Matrix multiplication
result = torch.matmul(tensor_a, tensor_b.T)

# Find max and min values
max_value = torch.max(result)
min_value = torch.min(result)

print("Result:\n", result)
print("Max value:", max_value)
print("Min value:", min_value)


Result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
Max value: tensor(0.5617)
Min value: tensor(0.3647)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
import torch

# Set the random seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor_4d = torch.rand(1, 1, 1, 10)

# Remove all dimensions of size 1
tensor_squeezed = tensor_4d.squeeze()

# Print both tensors and their shapes
print(tensor_4d, tensor_4d.shape)
print(tensor_squeezed, tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
